export { default as Home } from './Home'
export { default as Courses } from './Courses'
export { default as CourseDetail } from './CourseDetail'
export { default as MyCourses } from './MyCourses'
export { default as Favorites } from './Favorites'
export { default as Profile } from './Profile'
export { default as NotFound } from './NotFound'
